source "https://rubygems.org"

gem 'animation', '~> 0.1.alpha.3'
gem 'compass', '~> 1.1.0.alpha.3'
gem 'compass-core', '~> 1.1.0.alpha.3'
gem 'compass-import-once', '~> 1.0.5'
gem 'sass', '~> 3.4.9'

# gem 'chunky_png', '~> 1.3.3'
# gem 'coffee-script', '~> 2.3.0'
# gem 'coffee-script-source', '~> 1.8.0'
# gem 'execjs', '~> 2.2.2'
# gem 'json', '~> 1.8.1'
# gem 'listen', '~> 2.8.4'
